export const ROSTER_COLUMNS = [
  { key: 'name', label: '姓名', width: 70, type: 'text' },
  { key: 'employee_no', label: '员工编号', width: 90, type: 'text' },
  { key: 'id_card', label: '证件号码', width: 180, type: 'text' },
  { key: 'gender', label: '性别', width: 50, type: 'text' },
  { key: 'phone', label: '联系方式', width: 110, type: 'text' },
  { key: 'email', label: '邮箱', width: 150, type: 'text' },
  { key: 'work_place', label: '办公地点', width: 100, type: 'text' },
  { key: 'contract_company', label: '合同公司', width: 120, type: 'text' },
  { key: 'dept_level1', label: '1级部门', width: 100, type: 'text' },
  { key: 'dept_level2', label: '2级部门', width: 100, type: 'text' },
  { key: 'dept_level3', label: '3级部门', width: 100, type: 'text' },
  { key: 'dept_level4', label: '4级部门', width: 100, type: 'text' },
  { key: 'dept_level5', label: '5级部门', width: 100, type: 'text' },
  { key: 'department', label: '部门', width: 90, type: 'text' },
  { key: 'position', label: '职位', width: 90, type: 'text' },
  { key: 'employee_type', label: '员工类型', width: 80, type: 'text' },
  { key: 'position_level', label: '岗位职级', width: 80, type: 'text' },
  { key: 'job_level', label: '岗位级别', width: 80, type: 'text' },
  { key: 'status', label: '用工状态', width: 80, type: 'text' },
  { key: 'cost_owner', label: '成本归属', width: 90, type: 'text' },
  { key: 'report_manager', label: '直属主管', width: 80, type: 'text' },
  { key: 'entry_date', label: '入职时间', width: 100, type: 'text' },
  { key: 'regular_date', label: '计划转正日期', width: 110, type: 'text' },
  { key: 'regular_confirm_date', label: '转正时间', width: 100, type: 'text' },
  { key: 'resign_date', label: '离职日期', width: 100, type: 'text' },
  { key: 'birth_date', label: '出生日期', width: 100, type: 'text' },
  { key: 'age', label: '年龄', width: 50, type: 'int' },
  { key: 'nation', label: '民族', width: 60, type: 'text' },
  { key: 'marital_status', label: '婚姻状况', width: 70, type: 'text' },
  { key: 'children_status', label: '子女情况', width: 80, type: 'text' },
  { key: 'political_status', label: '政治面貌', width: 80, type: 'text' },
  { key: 'native_place', label: '籍贯', width: 100, type: 'text' },
  { key: 'residence_type', label: '户籍类型', width: 80, type: 'text' },
  { key: 'census_address', label: '户籍地址', width: 200, type: 'text' },
  { key: 'home_address', label: '家庭住址', width: 200, type: 'text' },
  { key: 'first_work_date', label: '首次参加工作时间', width: 120, type: 'text' },
  { key: 'company_tenure', label: '司龄', width: 70, type: 'text' },
  { key: 'work_tenure', label: '工龄', width: 70, type: 'text' },
  { key: 'education', label: '学历', width: 60, type: 'text' },
  { key: 'graduate_school', label: '毕业院校', width: 150, type: 'text' },
  { key: 'graduate_date', label: '毕业时间', width: 100, type: 'text' },
  { key: 'major', label: '所学专业', width: 100, type: 'text' },
  { key: 'cert1', label: '资格证/职称证1', width: 150, type: 'text' },
  { key: 'cert2', label: '资格证/职称证2', width: 150, type: 'text' },
  { key: 'emergency_contact_name', label: '紧急联系人姓名', width: 120, type: 'text' },
  { key: 'emergency_contact_relation', label: '联系人关系', width: 90, type: 'text' },
  { key: 'emergency_contact_phone', label: '联系人电话', width: 110, type: 'text' },
  { key: 'contract_start_date', label: '现合同起始日', width: 110, type: 'text' },
  { key: 'contract_end_date', label: '现合同到期日', width: 110, type: 'text' },
  { key: 'contract_type', label: '合同类型', width: 80, type: 'text' },
  { key: 'insurance_start_date', label: '五险一金起购日期', width: 130, type: 'text' },
  { key: 'insurance_location', label: '社保公积金购买地', width: 130, type: 'text' },
  { key: 'recruitment_channel', label: '招聘渠道', width: 100, type: 'text' },
  { key: 'hobby', label: '特长爱好', width: 100, type: 'text' },
  { key: 'commercial_insurance_type', label: '商业保险类型', width: 110, type: 'text' },
  { key: 'bank_card', label: '银行卡号', width: 180, type: 'text' },
  { key: 'bank_branch', label: '开户行', width: 120, type: 'text' },
  { key: 'bank_branch_detail', label: '开户行支行', width: 150, type: 'text' },
  { key: 'base_salary', label: '基本工资', width: 95, type: 'money' },
  { key: 'performance_standard', label: '绩效奖金标准', width: 110, type: 'money' },
  { key: 'meal_allowance', label: '餐补', width: 70, type: 'money' },
  { key: 'transport_allowance', label: '交通补贴', width: 80, type: 'money' },
  { key: 'communication_allowance', label: '通讯补贴', width: 80, type: 'money' },
  { key: 'computer_allowance', label: '电脑补贴', width: 80, type: 'money' },
  { key: 'housing_allowance', label: '住房补贴', width: 80, type: 'money' },
  { key: 'monthly_standard', label: '月薪标准', width: 90, type: 'money' },
  { key: 'salary_effective_date', label: '薪资生效日期', width: 110, type: 'text' },
  { key: 'remark', label: '备注', width: 200, type: 'text' },
]

export function getRosterFieldLabel(key) {
  const col = ROSTER_COLUMNS.find(c => c.key === key)
  return col ? col.label : key
}
