export const SALARY_COLUMNS = [
  { key: 'contract_company', label: '合同公司', width: 120, type: 'text', fixed: 'left',
    tooltip: '工资发放公司，拆分工资时会分别显示合同公司和北京易玖' },
  { key: 'employee_name', label: '姓名', width: 70, fixed: 'left', type: 'text',
    tooltip: '员工姓名，来源于员工档案' },
  { key: 'department', label: '部门', width: 90, type: 'text',
    tooltip: '员工所属部门，来源于员工档案' },
  { key: 'position', label: '职务', width: 90, type: 'text',
    tooltip: '员工职务，来源于员工档案' },
  { key: 'cost_owner', label: '费用负责人', width: 90, type: 'text',
    tooltip: '费用负责人，来源于员工档案' },
  { key: 'status', label: '状态', width: 80, type: 'text',
    tooltip: '员工用工状态' },
  { key: 'entry_date', label: '入职时间', width: 100, type: 'text',
    tooltip: '员工入职日期，来源于员工档案' },
  { key: 'total_work_days', label: '当月总计薪天数', width: 105, type: 'number',
    tooltip: '即应计薪天数，指当月标准总计薪天数，根据工作日历自动计算，用于薪资折算' },
  { key: 'actual_work_days', label: '实际计薪天数', width: 95, type: 'number',
    tooltip: '当月实际计薪天数，来源于考勤管理' },
  { key: 'attendance_rate', label: '出勤率', width: 75, type: 'percent',
    tooltip: '= 实际计薪天数 ÷ 当月总计薪天数 × 100%' },
  { key: 'base_salary', label: '基本工资', width: 95, type: 'money', summary: true,
    tooltip: '员工月基本工资，来源于员工薪资档案' },
  { key: 'commission_bonus', label: '提成/项目奖金/补发', width: 95, type: 'money', editable: true,
    tooltip: '当月提成/项目奖金/补发，手动录入或Excel导入' },
  { key: 'meal_allowance', label: '餐补', width: 70, type: 'money',
    tooltip: '每月固定餐费补贴，来源于员工薪资档案' },
  { key: 'transport_allowance', label: '交通补', width: 75, type: 'money',
    tooltip: '每月固定交通补贴，来源于员工薪资档案' },
  { key: 'communication_allowance', label: '通讯补', width: 75, type: 'money',
    tooltip: '每月固定通讯补贴，来源于员工薪资档案' },
  { key: 'computer_allowance', label: '电脑补贴（非固定收入）', width: 95, type: 'money',
    tooltip: '电脑补贴（非固定收入），仅当月有效，来源于员工薪资档案' },
  { key: 'housing_allowance', label: '住房补（非固定收入）', width: 95, type: 'money',
    tooltip: '住房补贴（非固定收入），仅当月有效，来源于员工薪资档案' },
  { key: 'allowance_total', label: '补贴合计', width: 85, type: 'money', summary: true,
    tooltip: '= 餐补+交通+通讯+电脑+住房补贴，自动计算' },
  { key: 'performance_standard', label: '绩效奖金标准', width: 95, type: 'money', summary: true,
    tooltip: '绩效奖金计算基数，来源于员工薪资档案' },
  { key: 'performance_coefficient', label: '实发绩效奖金系数', width: 95, type: 'number',
    tooltip: '当月绩效评分系数，来源于绩效管理模块' },
  { key: 'actual_performance', label: '实发绩效奖金标准', width: 95, type: 'money',
    tooltip: '= 绩效奖金标准 × 实发绩效奖金系数' },
  { key: 'effective_performance', label: '实发绩效奖金', width: 95, type: 'money',
    tooltip: '= 实发绩效奖金标准 × 出勤率' },
  { key: 'monthly_standard', label: '月薪标准', width: 90, type: 'money', summary: true,
    tooltip: '= 基本工资 + 绩效奖金标准 + 补贴合计，自动计算' },
  { key: 'gross_salary', label: '总应发工资', width: 100, type: 'money', summary: true,
    tooltip: '= (基本工资 + 补贴合计 + 提成/项目奖金/补发) × 出勤率 + 实发绩效奖金' },
  { key: 'pretax_adjustment', label: '税前调整金额', width: 90, type: 'money', editable: true,
    tooltip: '税前调整金额（如补发工资等），影响个税计算' },
  { key: 'pretax_adjustment_reason', label: '税前调整原因', width: 120, type: 'text', editable: true,
    tooltip: '税前调整的原因说明' },
  { key: 'pension_personal', label: '养老保险（个人）', width: 95, type: 'money',
    tooltip: '养老保险个人缴纳金额，来源于社保公积金表' },
  { key: 'unemployment_personal', label: '失业保险（个人）', width: 95, type: 'money',
    tooltip: '失业保险个人缴纳金额，来源于社保公积金表' },
  { key: 'medical_personal', label: '医疗保险（个人）', width: 95, type: 'money',
    tooltip: '医疗保险个人缴纳金额，来源于社保公积金表' },
  { key: 'housing_fund_personal', label: '公积金（个人）', width: 90, type: 'money',
    tooltip: '当月公积金个人缴纳金额，来源于社保公积金表' },
  { key: 'si_hf_total', label: '社保、公积金（个人）合计', width: 100, type: 'money', summary: true,
    tooltip: '= 养老保险 + 失业保险 + 医疗保险 + 公积金（均为个人部分）' },
  { key: 'salary_after_si_hf', label: '扣掉社保公积金工资', width: 110, type: 'money', summary: true, computed: true,
    tooltip: '= 总应发工资 + 税前调整 - 社保、公积金（个人）合计' },
  { key: 'tax_deduction', label: '本月应扣个税额', width: 100, type: 'money', editable: true,
    tooltip: '税务局申报后计算的应缴个税额，从本月工资代扣' },
  { key: 'posttax_adjustment', label: '税后调整金额', width: 90, type: 'money', editable: true,
    tooltip: '税后特殊调整（调休扣款等），不影响个税，只影响实发工资' },
  { key: 'posttax_adjustment_reason', label: '税后调整原因', width: 120, type: 'text', editable: true,
    tooltip: '税后调整的原因说明（如：临时性差旅补贴未报税费用），不填则报税金额应等于总应发工资' },
  { key: 'net_salary', label: '实发工资', width: 100, type: 'money', summary: true,
    tooltip: '= 总应发工资 - 社保、公积金合计 - 本月应扣个税额 + 税后调整金额' },
  { key: 'last_month_untaxed', label: '上月未报税金额', width: 100, type: 'money', editable: true,
    tooltip: '上月未报税金额，累计到本月工资报税' },
  { key: 'travel_untaxed', label: '临时性差旅补贴未报税费用', width: 100, type: 'money', editable: true,
    tooltip: '临时性差旅补贴未报税费用，来源于差旅报销表，计入本月工资报税' },
  { key: 'holiday_red_packet_untaxed', label: '节假日红包未报税', width: 100, type: 'money', editable: true,
    tooltip: '节假日红包未报税金额，需计入本月工资报税' },
  { key: 'actual_taxable', label: '本月实际工资报税金额', width: 120, type: 'money', summary: true,
    tooltip: '= 总应发工资 + 税前调整 + 上月未报税 + 差旅补贴未报税 + 节假日红包未报税（不含年终奖和补偿金，需单独报税）' },
  { key: 'severance_pay', label: '实发离职补偿金', width: 100, type: 'money', editable: true,
    tooltip: '实发离职补偿金（已扣税或免税部分），不影响当月工资个税' },
  { key: 'compensation_tax', label: '未报税补偿金', width: 100, type: 'money', editable: true,
    tooltip: '未报税补偿金，需单独使用补偿金报税模版申报' },
  { key: 'year_end_bonus_untaxed', label: '未报税年终奖', width: 100, type: 'money', editable: true,
    tooltip: '未报税年终奖，需单独使用年终奖报税模版申报' },
  { key: 'year_end_bonus_net', label: '实发年终奖', width: 100, type: 'money', editable: true,
    tooltip: '实发年终奖（扣个税后实际发放金额）' },
  { key: 'remark', label: '备注', width: 200, type: 'text', editable: true },
]

export const SALARY_EDITABLE_FIELDS = [
  'commission_bonus', 'pretax_adjustment', 'pretax_adjustment_reason',
  'posttax_adjustment', 'posttax_adjustment_reason',
  'severance_pay', 'year_end_bonus_untaxed', 'year_end_bonus_net',
  'last_month_untaxed', 'travel_untaxed', 'holiday_red_packet_untaxed', 'compensation_tax',
  'tax_deduction', 'remark'
]

export function getSalaryFieldLabel(key) {
  const col = SALARY_COLUMNS.find(c => c.key === key)
  return col ? col.label : key
}
